// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { anthropicBlock } from "./index";

export const anthropicBlockSchema = parseBlockSchema(anthropicBlock);
export const anthropicCredentialsSchema = parseBlockCredentials(
  anthropicBlock.id,
  auth.schema,
);
