/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutPricingRouteImport } from './routes/_layout/pricing'
import { Route as LayoutOssFriendsRouteImport } from './routes/_layout/oss-friends'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutSlugRouteImport } from './routes/_layout/$slug'
import { Route as LayoutTemplatesIndexRouteImport } from './routes/_layout/templates/index'
import { Route as LayoutBlogIndexRouteImport } from './routes/_layout/blog/index'
import { Route as LayoutTemplatesSlugRouteImport } from './routes/_layout/templates/$slug'
import { Route as LayoutBlogSlugRouteImport } from './routes/_layout/blog/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPricingRoute = LayoutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOssFriendsRoute = LayoutOssFriendsRouteImport.update({
  id: '/oss-friends',
  path: '/oss-friends',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlugRoute = LayoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesIndexRoute = LayoutTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogIndexRoute = LayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesSlugRoute = LayoutTemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBlogSlugRoute = LayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug': typeof LayoutSlugRoute
  '/about': typeof LayoutAboutRoute
  '/oss-friends': typeof LayoutOssFriendsRoute
  '/pricing': typeof LayoutPricingRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/blog/': typeof LayoutBlogIndexRoute
  '/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug': typeof LayoutSlugRoute
  '/about': typeof LayoutAboutRoute
  '/oss-friends': typeof LayoutOssFriendsRoute
  '/pricing': typeof LayoutPricingRoute
  '/blog/$slug': typeof LayoutBlogSlugRoute
  '/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/blog': typeof LayoutBlogIndexRoute
  '/templates': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_layout/$slug': typeof LayoutSlugRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/oss-friends': typeof LayoutOssFriendsRoute
  '/_layout/pricing': typeof LayoutPricingRoute
  '/_layout/blog/$slug': typeof LayoutBlogSlugRoute
  '/_layout/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/_layout/blog/': typeof LayoutBlogIndexRoute
  '/_layout/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/sitemap.xml'
    | '/$slug'
    | '/about'
    | '/oss-friends'
    | '/pricing'
    | '/blog/$slug'
    | '/templates/$slug'
    | '/blog/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/sitemap.xml'
    | '/$slug'
    | '/about'
    | '/oss-friends'
    | '/pricing'
    | '/blog/$slug'
    | '/templates/$slug'
    | '/blog'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/healthz'
    | '/sitemap.xml'
    | '/_layout/$slug'
    | '/_layout/about'
    | '/_layout/oss-friends'
    | '/_layout/pricing'
    | '/_layout/blog/$slug'
    | '/_layout/templates/$slug'
    | '/_layout/blog/'
    | '/_layout/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/pricing': {
      id: '/_layout/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LayoutPricingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/oss-friends': {
      id: '/_layout/oss-friends'
      path: '/oss-friends'
      fullPath: '/oss-friends'
      preLoaderRoute: typeof LayoutOssFriendsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$slug': {
      id: '/_layout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof LayoutSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/': {
      id: '/_layout/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof LayoutTemplatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/': {
      id: '/_layout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof LayoutBlogIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/$slug': {
      id: '/_layout/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof LayoutTemplatesSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/blog/$slug': {
      id: '/_layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof LayoutBlogSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSlugRoute: typeof LayoutSlugRoute
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutOssFriendsRoute: typeof LayoutOssFriendsRoute
  LayoutPricingRoute: typeof LayoutPricingRoute
  LayoutBlogSlugRoute: typeof LayoutBlogSlugRoute
  LayoutTemplatesSlugRoute: typeof LayoutTemplatesSlugRoute
  LayoutBlogIndexRoute: typeof LayoutBlogIndexRoute
  LayoutTemplatesIndexRoute: typeof LayoutTemplatesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSlugRoute: LayoutSlugRoute,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutOssFriendsRoute: LayoutOssFriendsRoute,
  LayoutPricingRoute: LayoutPricingRoute,
  LayoutBlogSlugRoute: LayoutBlogSlugRoute,
  LayoutTemplatesSlugRoute: LayoutTemplatesSlugRoute,
  LayoutBlogIndexRoute: LayoutBlogIndexRoute,
  LayoutTemplatesIndexRoute: LayoutTemplatesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  HealthzRoute: HealthzRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
