// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { litellmBlock } from "./index";

export const litellmBlockSchema = parseBlockSchema(litellmBlock);
export const litellmCredentialsSchema = parseBlockCredentials(
  litellmBlock.id,
  auth,
);
