// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { zendeskChatBlock } from '.'
import { auth } from './auth'

export const zendeskChatBlockSchema = parseBlockSchema(zendeskChatBlock)
export const zendeskChatCredentialsSchema = parseBlockCredentials(
  zendeskChatBlock.id,
  auth.schema
)
