// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { blinkBlock } from ".";
import { auth } from "./auth";

export const blinkBlockSchema = parseBlockSchema(blinkBlock);
export const blinkCredentialsSchema = parseBlockCredentials(
  blinkBlock.id,
  auth.schema,
);
