packages:
  - 'packages/*'
  - 'packages/deprecated/*'
  - 'packages/embeds/*'
  - 'packages/forge/*'
  - 'packages/forge/blocks/*'
  - 'apps/*'
  - 'packages/transactional/.react-email'
  - 'ee/packages/*'
  - 'ee/apps/*'
