// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@sniper.io/forge'
import { zemanticAiBlock } from '.'

export const zemanticAiBlockSchema = parseBlockSchema(zemanticAiBlock)
export const zemanticAiCredentialsSchema =
  parseBlockCredentials(zemanticAiBlock)
