// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@sniper.io/forge'
import { elevenlabsBlock } from '.'

export const elevenlabsBlockSchema = parseBlockSchema(elevenlabsBlock)
export const elevenlabsCredentialsSchema =
  parseBlockCredentials(elevenlabsBlock)
