// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@sniper.io/forge'
import { anthropicBlock } from '.'

export const anthropicBlockSchema = parseBlockSchema(anthropicBlock)
export const anthropicCredentialsSchema = parseBlockCredentials(anthropicBlock)
