// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@sniper.io/forge'
import { calComBlock } from '.'

export const calComBlockSchema = parseBlockSchema(calComBlock)
export const calComCredentialsSchema = parseBlockCredentials(calComBlock)
