// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { openAIBlock } from "./index";

export const openAIBlockSchema = parseBlockSchema(openAIBlock);
export const openAICredentialsSchema = parseBlockCredentials(
  openAIBlock.id,
  auth.schema,
);
