// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { mistralBlock } from "./index";

export const mistralBlockSchema = parseBlockSchema(mistralBlock);
export const mistralCredentialsSchema = parseBlockCredentials(
  mistralBlock.id,
  auth.schema,
);
