// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { segmentBlock } from "./index";

export const segmentBlockSchema = parseBlockSchema(segmentBlock);
export const segmentCredentialsSchema = parseBlockCredentials(
  segmentBlock.id,
  auth.schema,
);
