// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { segmentBlock } from '.'
import { auth } from './auth'

export const segmentBlockSchema = parseBlockSchema(segmentBlock)
export const segmentCredentialsSchema = parseBlockCredentials(
  segmentBlock.id,
  auth.schema
)
