// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { instantchatBlock } from '.'

export const instantchatBlockSchema = parseBlockSchema(instantchatBlock)
export const instantchatCredentialsSchema =
  parseBlockCredentials(instantchatBlock)
