// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { difyAiBlock } from "./index";

export const difyAiBlockSchema = parseBlockSchema(difyAiBlock);
export const difyAiCredentialsSchema = parseBlockCredentials(
  difyAiBlock.id,
  auth.schema,
);
