// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@sniper.io/forge'
import { openAIBlock } from '.'

export const openAIBlockSchema = parseBlockSchema(openAIBlock)
export const openAICredentialsSchema = parseBlockCredentials(openAIBlock)
