const allTimeZones = [
  { places: "Midway Island, Samoa", timeZone: "Pacific/Midway" },
  { places: "Hawaii", timeZone: "Pacific/Honolulu" },
  { places: "Alaska", timeZone: "America/Juneau" },
  { places: "Mountain Time", timeZone: "America/Boise" },
  { places: "Dawson, Yukon", timeZone: "America/Dawson" },
  { places: "Chihuahua, La Paz, Mazatlan", timeZone: "America/Chihuahua" },
  { places: "Arizona", timeZone: "America/Phoenix" },
  { places: "Central Time", timeZone: "America/Chicago" },
  { places: "Saskatchewan", timeZone: "America/Regina" },
  {
    places: "Guadalajara, Mexico City, Monterrey",
    timeZone: "America/Mexico_City",
  },
  { places: "Central America", timeZone: "America/Belize" },
  { places: "Eastern Time", timeZone: "America/Detroit" },
  { places: "Bogota, Lima, Quito", timeZone: "America/Bogota" },
  { places: "Caracas, La Paz", timeZone: "America/Caracas" },
  { places: "Santiago", timeZone: "America/Santiago" },
  { places: "Newfoundland and Labrador", timeZone: "America/St_Johns" },
  { places: "Brasilia", timeZone: "America/Sao_Paulo" },
  { places: "Tijuana", timeZone: "America/Tijuana" },
  { places: "Montevideo", timeZone: "America/Montevideo" },
  {
    places: "Buenos Aires, Georgetown",
    timeZone: "America/Argentina/Buenos_Aires",
  },
  { places: "Greenland", timeZone: "America/Godthab" },
  { places: "Pacific Time", timeZone: "America/Los_Angeles" },
  { places: "Azores", timeZone: "Atlantic/Azores" },
  { places: "Cape Verde Islands", timeZone: "Atlantic/Cape_Verde" },
  { places: "UTC", timeZone: "GMT" },
  { places: "Edinburgh, London", timeZone: "Europe/London" },
  { places: "Dublin", timeZone: "Europe/Dublin" },
  { places: "Lisbon", timeZone: "Europe/Lisbon" },
  { places: "Casablanca, Monrovia", timeZone: "Africa/Casablanca" },
  { places: "Canary Islands", timeZone: "Atlantic/Canary" },
  {
    places: "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    timeZone: "Europe/Belgrade",
  },
  { places: "Sarajevo, Skopje, Warsaw, Zagreb", timeZone: "Europe/Sarajevo" },
  {
    places: "Brussels, Copenhagen, Madrid, Paris",
    timeZone: "Europe/Brussels",
  },
  {
    places: "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    timeZone: "Europe/Amsterdam",
  },
  { places: "West Central Africa", timeZone: "Africa/Algiers" },
  { places: "Bucharest", timeZone: "Europe/Bucharest" },
  { places: "Cairo", timeZone: "Africa/Cairo" },
  {
    places: "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    timeZone: "Europe/Helsinki",
  },
  { places: "Athens", timeZone: "Europe/Athens" },
  { places: "Jerusalem", timeZone: "Asia/Jerusalem" },
  { places: "Harare, Pretoria", timeZone: "Africa/Harare" },
  {
    places: "Istanbul, Minsk, Moscow, St. Petersburg, Volgograd",
    timeZone: "Europe/Moscow",
  },
  { places: "Kuwait, Riyadh", timeZone: "Asia/Kuwait" },
  { places: "Nairobi", timeZone: "Africa/Nairobi" },
  { places: "Baghdad", timeZone: "Asia/Baghdad" },
  { places: "Tehran", timeZone: "Asia/Tehran" },
  { places: "Abu Dhabi, Muscat", timeZone: "Asia/Dubai" },
  { places: "Baku, Tbilisi, Yerevan", timeZone: "Asia/Baku" },
  { places: "Kabul", timeZone: "Asia/Kabul" },
  { places: "Ekaterinburg", timeZone: "Asia/Yekaterinburg" },
  { places: "Islamabad, Karachi, Tashkent", timeZone: "Asia/Karachi" },
  { places: "Chennai, Kolkata, Mumbai, New Delhi", timeZone: "Asia/Kolkata" },
  { places: "Kathmandu", timeZone: "Asia/Kathmandu" },
  { places: "Astana, Dhaka", timeZone: "Asia/Dhaka" },
  { places: "Sri Jayawardenepura", timeZone: "Asia/Colombo" },
  { places: "Almaty, Novosibirsk", timeZone: "Asia/Almaty" },
  { places: "Yangon Rangoon", timeZone: "Asia/Rangoon" },
  { places: "Bangkok, Hanoi, Jakarta", timeZone: "Asia/Bangkok" },
  { places: "Krasnoyarsk", timeZone: "Asia/Krasnoyarsk" },
  {
    places: "Beijing, Chongqing, Hong Kong SAR, Urumqi",
    timeZone: "Asia/Shanghai",
  },
  { places: "Kuala Lumpur, Singapore", timeZone: "Asia/Kuala_Lumpur" },
  { places: "Taipei", timeZone: "Asia/Taipei" },
  { places: "Perth", timeZone: "Australia/Perth" },
  { places: "Irkutsk, Ulaanbaatar", timeZone: "Asia/Irkutsk" },
  { places: "Seoul", timeZone: "Asia/Seoul" },
  { places: "Osaka, Sapporo, Tokyo", timeZone: "Asia/Tokyo" },
  { places: "Yakutsk", timeZone: "Asia/Yakutsk" },
  { places: "Darwin", timeZone: "Australia/Darwin" },
  { places: "Adelaide", timeZone: "Australia/Adelaide" },
  { places: "Canberra, Melbourne, Sydney", timeZone: "Australia/Sydney" },
  { places: "Brisbane", timeZone: "Australia/Brisbane" },
  { places: "Hobart", timeZone: "Australia/Hobart" },
  { places: "Vladivostok", timeZone: "Asia/Vladivostok" },
  { places: "Guam, Port Moresby", timeZone: "Pacific/Guam" },
  {
    places: "Magadan, Solomon Islands, New Caledonia",
    timeZone: "Asia/Magadan",
  },
  { places: "Kamchatka, Marshall Islands", timeZone: "Asia/Kamchatka" },
  { places: "Fiji Islands", timeZone: "Pacific/Fiji" },
  { places: "Auckland, Wellington", timeZone: "Pacific/Auckland" },
  { places: "Nuku'alofa", timeZone: "Pacific/Tongatapu" },
];

export default allTimeZones;
