// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { dataforseoBlock } from '.'

export const dataforseoBlockSchema = parseBlockSchema(dataforseoBlock)
export const dataforseoCredentialsSchema =
  parseBlockCredentials(dataforseoBlock)
