#!/usr/bin/env bun
import type { DMMF, GeneratorOptions } from "@prisma/generator-helper";
import { generatorHandler } from "@prisma/generator-helper";
import { mkdir, writeFile } from "fs/promises";
import { dirname } from "path";

const header =
  "// This file was generated by prisma-effect-generator, do not edit manually.\n";

type ModelMapping = {
  model: string;
  createManyAndReturn?: string | null;
  updateManyAndReturn?: string | null;
};

const toCamelCase = (string_: string) =>
  string_.charAt(0).toLowerCase() + string_.slice(1);

const hasTypedSqlSupport = (options: GeneratorOptions) =>
  options.typedSql !== undefined ||
  [options.generator, ...options.otherGenerators].some((generator) =>
    generator.previewFeatures.includes("typedSql"),
  );

const getModelMappings = (options: GeneratorOptions) =>
  new Map(
    options.dmmf.mappings.modelOperations.map((modelMapping) => [
      modelMapping.model,
      modelMapping,
    ]),
  );

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/effect.ts",
      prettyName: "Prisma Effect Generator",
    };
  },

  async onGenerate(options) {
    const outputPath = options.generator.output?.value;
    const clientImportPath = options.generator.config.clientImportPath;

    if (!outputPath)
      throw new Error("effect-prisma-generator: No outputPath specified");
    if (Array.isArray(clientImportPath)) {
      throw new Error(
        "effect-prisma-generator: clientImportPath must be a string. Array given.",
      );
    }
    if (typeof clientImportPath !== "string") {
      throw new Error("effect-prisma-generator: No clientImportPath specified");
    }
    if (!outputPath.toLowerCase().endsWith(".ts")) {
      throw new Error("effect-prisma-generator: outputPath must be a ts file");
    }

    await mkdir(dirname(outputPath), { recursive: true });

    await generateUnifiedService({
      models: options.dmmf.datamodel.models,
      outputPath,
      clientImportPath,
      hasTypedSql: hasTypedSqlSupport(options),
      modelMappings: getModelMappings(options),
    });
  },
});

const generateRawSqlOperations = (hasTypedSql: boolean) =>
  [
    `$executeRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$executeRaw(args[0], ...args.slice(1)) : client.$executeRaw(args)),
          catch: (error) => mapError(error, "$executeRaw", "Prisma")
        }),
      )`,
    `$executeRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$executeRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$executeRawUnsafe", "Prisma")
        }),
      )`,
    `$queryRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$queryRaw(args[0], ...args.slice(1)) : client.$queryRaw(args)),
          catch: (error) => mapError(error, "$queryRaw", "Prisma")
        }),
      )`,
    `$queryRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$queryRawUnsafe", "Prisma")
        }),
      )`,
    hasTypedSql
      ? `$queryRawTyped: <T>(typedQuery: runtime.TypedSql<unknown[], T>) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawTyped(typedQuery),
          catch: (error) => mapError(error, "$queryRawTyped", "Prisma")
        }),
      )`
      : null,
  ]
    .filter((operation): operation is string => operation !== null)
    .map((operation) => `    ${operation}`)
    .join(",\n\n");

const generateModelOperations = (
  models: readonly DMMF.Model[],
  modelMappings: Map<string, ModelMapping>,
) =>
  models
    .map((model) => {
      const modelName = model.name;
      const modelNameCamel = toCamelCase(modelName);
      const modelMapping = modelMappings.get(modelName);

      const operations = [
        `findUnique: <T extends Prisma.${modelName}FindUniqueArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindUniqueArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findUnique(args),
            catch: (error) => mapFindError(error, "findUnique", "${modelName}")
          }),
        )`,
        `findUniqueOrThrow: <T extends Prisma.${modelName}FindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindUniqueOrThrowArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findUniqueOrThrow(args),
            catch: (error) => mapFindOrThrowError(error, "findUniqueOrThrow", "${modelName}")
          }),
        )`,
        `findFirst: <T extends Prisma.${modelName}FindFirstArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindFirstArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findFirst(args),
            catch: (error) => mapFindError(error, "findFirst", "${modelName}")
          }),
        )`,
        `findFirstOrThrow: <T extends Prisma.${modelName}FindFirstOrThrowArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindFirstOrThrowArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findFirstOrThrow(args),
            catch: (error) => mapFindOrThrowError(error, "findFirstOrThrow", "${modelName}")
          }),
        )`,
        `findMany: <T extends Prisma.${modelName}FindManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findMany(args),
            catch: (error) => mapFindError(error, "findMany", "${modelName}")
          }),
        )`,
        `create: <T extends Prisma.${modelName}CreateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.create(args),
            catch: (error) => mapCreateError(error, "create", "${modelName}")
          }),
        )`,
        `createMany: <T extends Prisma.${modelName}CreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.createMany(args),
            catch: (error) => mapCreateError(error, "createMany", "${modelName}")
          }),
        )`,
        modelMapping?.createManyAndReturn
          ? `createManyAndReturn: <T extends Prisma.${modelName}CreateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateManyAndReturnArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.createManyAndReturn(args),
            catch: (error) => mapCreateError(error, "createManyAndReturn", "${modelName}")
          }),
        )`
          : null,
        `delete: <T extends Prisma.${modelName}DeleteArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}DeleteArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.delete(args),
            catch: (error) => mapDeleteError(error, "delete", "${modelName}")
          }),
        )`,
        `update: <T extends Prisma.${modelName}UpdateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.update(args),
            catch: (error) => mapUpdateError(error, "update", "${modelName}")
          }),
        )`,
        `deleteMany: <T extends Prisma.${modelName}DeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}DeleteManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.deleteMany(args),
            catch: (error) => mapDeleteManyError(error, "deleteMany", "${modelName}")
          }),
        )`,
        `updateMany: <T extends Prisma.${modelName}UpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.updateMany(args),
            catch: (error) => mapUpdateManyError(error, "updateMany", "${modelName}")
          }),
        )`,
        modelMapping?.updateManyAndReturn
          ? `updateManyAndReturn: <T extends Prisma.${modelName}UpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateManyAndReturnArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.updateManyAndReturn(args),
            catch: (error) => mapUpdateManyError(error, "updateManyAndReturn", "${modelName}")
          }),
        )`
          : null,
        `upsert: <T extends Prisma.${modelName}UpsertArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpsertArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.upsert(args),
            catch: (error) => mapCreateError(error, "upsert", "${modelName}")
          }),
        )`,
        `count: <T extends Prisma.${modelName}CountArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CountArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.count(args),
            catch: (error) => mapFindError(error, "count", "${modelName}")
          }),
        )`,
        `aggregate: <T extends Prisma.${modelName}AggregateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}AggregateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.aggregate(args),
            catch: (error) => mapFindError(error, "aggregate", "${modelName}")
          }),
        )`,
        `groupBy: <
        T extends Prisma.${modelName}GroupByArgs,
        HasSelectOrTake extends Prisma.Or<
          Prisma.Extends<'skip', Prisma.Keys<T>>,
          Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
          ? { orderBy: Prisma.${modelName}GroupByArgs['orderBy'] }
          : { orderBy?: Prisma.${modelName}GroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
        ? \`Error: "by" must not be empty.\`
        : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
              ? \`Error: Field "\${P}" used in "having" needs to be provided in "by".\`
              : [
                  Error,
                  'Field ',
                  P,
                  \` in "having" needs to be provided in "by"\`,
                ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
              }[OrderFields]
          : 'Error: If you provide "skip", you also need to provide "orderBy"'
        : ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
          }[OrderFields]
      >(args: Prisma.SubsetIntersection<T, Prisma.${modelName}GroupByArgs, OrderByArg> & InputErrors) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.groupBy(args as any) as Prisma.PrismaPromise<
              Array<Prisma.PickEnumerable<Prisma.${modelName}GroupByOutputType, T["by"]> & {
                  [P in keyof T &
                    keyof Prisma.${modelName}GroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                      ? number
                      : Prisma.GetScalarType<
                          T[P],
                          Prisma.${modelName}GroupByOutputType[P]
                        >
                    : Prisma.GetScalarType<
                        T[P],
                        Prisma.${modelName}GroupByOutputType[P]
                      >;
                }>>,
            catch: (error) => mapFindError(error, "groupBy", "${modelName}")
          }),
        )`,
      ]
        .filter((operation): operation is string => operation !== null)
        .map((operation) => `      ${operation}`)
        .join(",\n\n");

      return `    ${modelNameCamel}: {\n${operations}\n    }`;
    })
    .join(",\n\n");

const generateUnifiedService = async ({
  models,
  outputPath,
  clientImportPath,
  hasTypedSql,
  modelMappings,
}: {
  models: readonly DMMF.Model[];
  outputPath: string;
  clientImportPath: string;
  hasTypedSql: boolean;
  modelMappings: Map<string, ModelMapping>;
}) => {
  const rawSqlOperations = generateRawSqlOperations(hasTypedSql);
  const modelOperations = generateModelOperations(models, modelMappings);
  const runtimeImport = hasTypedSql
    ? '\nimport * as runtime from "@prisma/client/runtime/client"'
    : "";

  const serviceContent = `${header}
import { Cause, Data, Effect, Exit, Layer, Option, ServiceMap } from "effect"
import { Prisma, PrismaClient } from "${clientImportPath}"${runtimeImport}

export class PrismaClientService extends ServiceMap.Service<
  PrismaClientService,
  PrismaClient
>()("PrismaClientService") {}

export class PrismaTransactionClientService extends ServiceMap.Service<
  PrismaTransactionClientService,
  Prisma.TransactionClient
>()("PrismaTransactionClientService") {}

export class PrismaUniqueConstraintError extends Data.TaggedError("PrismaUniqueConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaForeignKeyConstraintError extends Data.TaggedError("PrismaForeignKeyConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRecordNotFoundError extends Data.TaggedError("PrismaRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelationViolationError extends Data.TaggedError("PrismaRelationViolationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelatedRecordNotFoundError extends Data.TaggedError("PrismaRelatedRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaTransactionConflictError extends Data.TaggedError("PrismaTransactionConflictError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueTooLongError extends Data.TaggedError("PrismaValueTooLongError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueOutOfRangeError extends Data.TaggedError("PrismaValueOutOfRangeError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaDbConstraintError extends Data.TaggedError("PrismaDbConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaConnectionError extends Data.TaggedError("PrismaConnectionError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaMissingRequiredValueError extends Data.TaggedError("PrismaMissingRequiredValueError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaInputValidationError extends Data.TaggedError("PrismaInputValidationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export type PrismaCreateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaDeleteError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaFindOrThrowError =
  | PrismaConnectionError
  | PrismaRecordNotFoundError

export type PrismaFindError =
  | PrismaConnectionError

export type PrismaDeleteManyError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateManyError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

const mapError = (error: unknown, operation: string, model: string): PrismaError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapCreateError = (error: unknown, operation: string, model: string): PrismaCreateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapUpdateError = (error: unknown, operation: string, model: string): PrismaUpdateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapDeleteError = (error: unknown, operation: string, model: string): PrismaDeleteError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapFindOrThrowError = (error: unknown, operation: string, model: string): PrismaFindOrThrowError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapFindError = (error: unknown, operation: string, model: string): PrismaFindError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapDeleteManyError = (error: unknown, operation: string, model: string): PrismaDeleteManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const mapUpdateManyError = (error: unknown, operation: string, model: string): PrismaUpdateManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const clientOrTx = (client: PrismaClient) =>
  Effect.map(
    Effect.serviceOption(PrismaTransactionClientService),
    Option.getOrElse(() => client),
  );

const makePrismaService = Effect.gen(function* () {
  const client = yield* PrismaClientService;
  return {
      $transaction: Effect.fn("PrismaService.$transaction")(
        function* <A, E, R>(
          effect: Effect.Effect<A, E, R>,
          options?: {
            maxWait?: number
            timeout?: number
            isolationLevel?: Prisma.TransactionIsolationLevel
          }
        ) {
          const services = yield* Effect.services<R>();
          const tx = yield* Effect.serviceOption(PrismaTransactionClientService);
          return yield* Option.match(tx, {
            onSome: (_tx) => effect,
            onNone: () => Effect.tryPromise({
              try: () =>
                client.$transaction(async (tx) => {
                  const exit = await Effect.runPromiseExitWith(services)(
                    effect.pipe(Effect.provideService(PrismaTransactionClientService, tx)) as Effect.Effect<A, E, R>,
                  )
                  if (Exit.isSuccess(exit)) {
                    return exit.value
                  }
                  throw Cause.squash(exit.cause)
                }, options),
              catch: (error) => error as E,
            }) as unknown as Effect.Effect<A, E, R>,
          })
        },
      ),
${rawSqlOperations ? `\n${rawSqlOperations},\n` : ""}
${modelOperations}
  }
})

type PrismaServiceShape = Effect.Success<typeof makePrismaService>

export class PrismaService extends ServiceMap.Service<
  PrismaService,
  PrismaServiceShape
>()("PrismaService") {
  static readonly layer = Layer.effect(PrismaService, makePrismaService)
}
`;

  await writeFile(outputPath, serviceContent);
};
