// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { googlePlacesAutocompleteBlock } from '.'
import { auth } from './auth'

export const googlePlacesAutocompleteBlockSchema = parseBlockSchema(googlePlacesAutocompleteBlock)
export const googlePlacesAutocompleteCredentialsSchema = parseBlockCredentials(googlePlacesAutocompleteBlock.id, auth)