// Do not edit this file manually
import { anthropicBlock } from "@typebot.io/anthropic-block";
import { calComBlock } from "@typebot.io/cal-com-block";
import { chatNodeBlock } from "@typebot.io/chat-node-block";
import { difyAiBlock } from "@typebot.io/dify-ai-block";
import { elevenlabsBlock } from "@typebot.io/elevenlabs-block";
import { groqBlock } from "@typebot.io/groq-block";
import { mistralBlock } from "@typebot.io/mistral-block";
import { nocodbBlock } from "@typebot.io/nocodb-block";
import { openRouterBlock } from "@typebot.io/open-router-block";
import { openAIBlock } from "@typebot.io/openai-block";
import { qrCodeBlock } from "@typebot.io/qrcode-block";
import { segmentBlock } from "@typebot.io/segment-block";
import { togetherAiBlock } from "@typebot.io/together-ai-block";
import { zendeskBlock } from "@typebot.io/zendesk-block";

export const forgedBlocks = {
  [openAIBlock.id]: openAIBlock,
  [calComBlock.id]: calComBlock,
  [chatNodeBlock.id]: chatNodeBlock,
  [qrCodeBlock.id]: qrCodeBlock,
  [difyAiBlock.id]: difyAiBlock,
  [mistralBlock.id]: mistralBlock,
  [elevenlabsBlock.id]: elevenlabsBlock,
  [anthropicBlock.id]: anthropicBlock,
  [togetherAiBlock.id]: togetherAiBlock,
  [openRouterBlock.id]: openRouterBlock,
  [nocodbBlock.id]: nocodbBlock,
  [segmentBlock.id]: segmentBlock,
  [groqBlock.id]: groqBlock,
  [zendeskBlock.id]: zendeskBlock,
};
export type ForgedBlockDefinition =
  (typeof forgedBlocks)[keyof typeof forgedBlocks];
