// Do not edit this file manually
import { anthropicBlock } from "@typebot.io/anthropic-block";
import anthropicBlockHandlers from "@typebot.io/anthropic-block/handlers";
import { blinkBlock } from "@typebot.io/blink-block";
import blinkBlockHandlers from "@typebot.io/blink-block/handlers";
import { calComBlock } from "@typebot.io/cal-com-block";
import calComBlockHandlers from "@typebot.io/cal-com-block/handlers";
import { chatNodeBlock } from "@typebot.io/chat-node-block";
import chatNodeBlockHandlers from "@typebot.io/chat-node-block/handlers";
import { deepSeekBlock } from "@typebot.io/deepseek-block";
import deepSeekBlockHandlers from "@typebot.io/deepseek-block/handlers";
import { difyAiBlock } from "@typebot.io/dify-ai-block";
import difyAiBlockHandlers from "@typebot.io/dify-ai-block/handlers";
import { elevenlabsBlock } from "@typebot.io/elevenlabs-block";
import elevenlabsBlockHandlers from "@typebot.io/elevenlabs-block/handlers";
import { gmailBlock } from "@typebot.io/gmail-block";
import gmailBlockHandlers from "@typebot.io/gmail-block/handlers";
import { groqBlock } from "@typebot.io/groq-block";
import groqBlockHandlers from "@typebot.io/groq-block/handlers";
import { mistralBlock } from "@typebot.io/mistral-block";
import mistralBlockHandlers from "@typebot.io/mistral-block/handlers";
import { nocodbBlock } from "@typebot.io/nocodb-block";
import nocodbBlockHandlers from "@typebot.io/nocodb-block/handlers";
import { openRouterBlock } from "@typebot.io/open-router-block";
import openRouterBlockHandlers from "@typebot.io/open-router-block/handlers";
import { openAIBlock } from "@typebot.io/openai-block";
import openAIBlockHandlers from "@typebot.io/openai-block/handlers";
import { perplexityBlock } from "@typebot.io/perplexity-block";
import perplexityBlockHandlers from "@typebot.io/perplexity-block/handlers";
import { posthogBlock } from "@typebot.io/posthog-block";
import posthogBlockHandlers from "@typebot.io/posthog-block/handlers";
import { qrCodeBlock } from "@typebot.io/qrcode-block";
import qrCodeBlockHandlers from "@typebot.io/qrcode-block/handlers";
import { segmentBlock } from "@typebot.io/segment-block";
import segmentBlockHandlers from "@typebot.io/segment-block/handlers";
import { togetherAiBlock } from "@typebot.io/together-ai-block";
import togetherAiBlockHandlers from "@typebot.io/together-ai-block/handlers";
import { zendeskBlock } from "@typebot.io/zendesk-block";
import zendeskBlockHandlers from "@typebot.io/zendesk-block/handlers";

export const forgedBlockHandlers = {
  [openAIBlock.id]: openAIBlockHandlers,
  [calComBlock.id]: calComBlockHandlers,
  [chatNodeBlock.id]: chatNodeBlockHandlers,
  [qrCodeBlock.id]: qrCodeBlockHandlers,
  [difyAiBlock.id]: difyAiBlockHandlers,
  [mistralBlock.id]: mistralBlockHandlers,
  [elevenlabsBlock.id]: elevenlabsBlockHandlers,
  [anthropicBlock.id]: anthropicBlockHandlers,
  [togetherAiBlock.id]: togetherAiBlockHandlers,
  [openRouterBlock.id]: openRouterBlockHandlers,
  [nocodbBlock.id]: nocodbBlockHandlers,
  [segmentBlock.id]: segmentBlockHandlers,
  [groqBlock.id]: groqBlockHandlers,
  [zendeskBlock.id]: zendeskBlockHandlers,
  [posthogBlock.id]: posthogBlockHandlers,
  [perplexityBlock.id]: perplexityBlockHandlers,
  [deepSeekBlock.id]: deepSeekBlockHandlers,
  [blinkBlock.id]: blinkBlockHandlers,
  [gmailBlock.id]: gmailBlockHandlers,
};
