// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { openRouterBlock } from "./index";

export const openRouterBlockSchema = parseBlockSchema(openRouterBlock);
export const openRouterCredentialsSchema = parseBlockCredentials(
  openRouterBlock.id,
  auth.schema,
);
