// Do not edit this file manually
import { ForgedBlock } from './types'

export const forgedBlockIds = [
  'openai',
  'cal-com',
  'chat-node',
  'qr-code',
  'dify-ai',
  'mistral',
  'elevenlabs',
  'anthropic',
  'together-ai',
  'open-router',
  'nocodb',
  'segment',
  'groq',
  'zendesk-messaging',
] as const satisfies ForgedBlock['type'][]
