// Do not edit this file manually
import { anthropicBlock } from '@sniper.io/anthropic-block'
import { openRouterBlock } from '@sniper.io/open-router-block'
import { togetherAiBlock } from '@sniper.io/together-ai-block'
import { elevenlabsBlock } from '@sniper.io/elevenlabs-block'
import { difyAiBlock } from '@sniper.io/dify-ai-block'
import { mistralBlock } from '@sniper.io/mistral-block'
import { qrCodeBlock } from '@sniper.io/qrcode-block'
import { chatNodeBlock } from '@sniper.io/chat-node-block'
import { calComBlock } from '@sniper.io/cal-com-block'
import { zemanticAiBlock } from '@sniper.io/zemantic-ai-block'
import { openAIBlock } from '@sniper.io/openai-block'
import { nocodbBlock } from '@sniper.io/nocodb-block'

export const forgedBlocks = {
  [openAIBlock.id]: openAIBlock,
  [zemanticAiBlock.id]: zemanticAiBlock,
  [calComBlock.id]: calComBlock,
  [chatNodeBlock.id]: chatNodeBlock,
  [qrCodeBlock.id]: qrCodeBlock,
  [difyAiBlock.id]: difyAiBlock,
  [mistralBlock.id]: mistralBlock,
  [elevenlabsBlock.id]: elevenlabsBlock,
  [anthropicBlock.id]: anthropicBlock,
  [togetherAiBlock.id]: togetherAiBlock,
  [openRouterBlock.id]: openRouterBlock,
  [nocodbBlock.id]: nocodbBlock,
}
