// Do not edit this file manually
export const enabledBlocks = [
  'openai',
  'zemantic-ai',
  'cal-com',
  'chat-node',
  'qr-code',
  'dify-ai',
  'mistral',
  'paystack',
  'razorpay',
] as const
