// Do not edit this file manually
export const enabledBlocks = [
  'openai',
  'zemantic-ai',
  'cal-com',
  'chat-node',
  'qr-code',
  'dify-ai',
  'mistral',
  'elevenlabs',
  'anthropic',
  'together-ai',
  'open-router',
  'nocodb',
] as const
