// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { fraseIoBlock } from '.'

export const fraseIoBlockSchema = parseBlockSchema(fraseIoBlock)
export const fraseIoCredentialsSchema = parseBlockCredentials(fraseIoBlock)
