// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { gmailBlock } from ".";
import { auth } from "./auth";

export const gmailBlockSchema = parseBlockSchema(gmailBlock);
export const gmailCredentialsSchema = parseBlockCredentials(
  gmailBlock.id,
  auth,
);
