// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { groqBlock } from "./index";

export const groqBlockSchema = parseBlockSchema(groqBlock);
export const groqCredentialsSchema = parseBlockCredentials(
  groqBlock.id,
  auth.schema,
);
