// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { gandrBlock } from "./index";

export const gandrBlockSchema = parseBlockSchema(gandrBlock);
export const gandrCredentialsSchema = parseBlockCredentials(
  gandrBlock.id,
  auth,
);
