// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { chatNodeBlock } from "./index";

export const chatNodeBlockSchema = parseBlockSchema(chatNodeBlock);
export const chatNodeCredentialsSchema = parseBlockCredentials(
  chatNodeBlock.id,
  auth.schema,
);
