export const pricingData = {
  markets: [
    {
      market: "Argentina",
      currency: "$US",
      marketing: 0.0618,
      utility: 0.034,
      authentication: 0.0367,
      authenticationInternational: null,
      service: 0.0316,
    },
    {
      market: "Brazil",
      currency: "$US",
      marketing: 0.0625,
      utility: 0.008,
      authentication: 0.0315,
      authenticationInternational: null,
      service: 0.03,
    },
    {
      market: "Chile",
      currency: "$US",
      marketing: 0.0889,
      utility: 0.02,
      authentication: 0.0527,
      authenticationInternational: null,
      service: 0.0454,
    },
    {
      market: "Colombia",
      currency: "$US",
      marketing: 0.0125,
      utility: 0.0002,
      authentication: 0.0077,
      authenticationInternational: null,
      service: 0.006,
    },
    {
      market: "Egypt",
      currency: "$US",
      marketing: 0.1073,
      utility: 0.0052,
      authentication: 0.0618,
      authenticationInternational: null,
      service: 0.0644,
    },
    {
      market: "France",
      currency: "$US",
      marketing: 0.1432,
      utility: 0.03,
      authentication: 0.0691,
      authenticationInternational: null,
      service: 0.0859,
    },
    {
      market: "Germany",
      currency: "$US",
      marketing: 0.1365,
      utility: 0.055,
      authentication: 0.0768,
      authenticationInternational: null,
      service: 0.0819,
    },
    {
      market: "India",
      currency: "$US",
      marketing: 0.0107,
      utility: 0.0014,
      authentication: 0.0014,
      authenticationInternational: 0.028,
      service: 0.004,
    },
    {
      market: "Indonesia",
      currency: "$US",
      marketing: 0.0411,
      utility: 0.02,
      authentication: 0.03,
      authenticationInternational: 0.136,
      service: 0.019,
    },
    {
      market: "Israel",
      currency: "$US",
      marketing: 0.0353,
      utility: 0.0053,
      authentication: 0.0169,
      authenticationInternational: null,
      service: 0.018,
    },
    {
      market: "Italy",
      currency: "$US",
      marketing: 0.0691,
      utility: 0.03,
      authentication: 0.0378,
      authenticationInternational: null,
      service: 0.0386,
    },
    {
      market: "Malaysia",
      currency: "$US",
      marketing: 0.086,
      utility: 0.014,
      authentication: 0.018,
      authenticationInternational: null,
      service: 0.022,
    },
    {
      market: "Mexico",
      currency: "$US",
      marketing: 0.0436,
      utility: 0.01,
      authentication: 0.0239,
      authenticationInternational: null,
      service: 0.0105,
    },
    {
      market: "Netherlands",
      currency: "$US",
      marketing: 0.1597,
      utility: 0.05,
      authentication: 0.072,
      authenticationInternational: null,
      service: 0.0891,
    },
    {
      market: "Nigeria",
      currency: "$US",
      marketing: 0.0516,
      utility: 0.0067,
      authentication: 0.0287,
      authenticationInternational: null,
      service: 0.031,
    },
    {
      market: "Pakistan",
      currency: "$US",
      marketing: 0.0473,
      utility: 0.0054,
      authentication: 0.0228,
      authenticationInternational: null,
      service: 0.0142,
    },
    {
      market: "Peru",
      currency: "$US",
      marketing: 0.0703,
      utility: 0.02,
      authentication: 0.0377,
      authenticationInternational: null,
      service: 0.0179,
    },
    {
      market: "Russia",
      currency: "$US",
      marketing: 0.0802,
      utility: 0.04,
      authentication: 0.0429,
      authenticationInternational: null,
      service: 0.0398,
    },
    {
      market: "Saudi Arabia",
      currency: "$US",
      marketing: 0.0455,
      utility: 0.0115,
      authentication: 0.0226,
      authenticationInternational: null,
      service: 0.0195,
    },
    {
      market: "South Africa",
      currency: "$US",
      marketing: 0.0379,
      utility: 0.0076,
      authentication: 0.018,
      authenticationInternational: null,
      service: 0.0168,
    },
    {
      market: "Spain",
      currency: "$US",
      marketing: 0.0615,
      utility: 0.02,
      authentication: 0.0342,
      authenticationInternational: null,
      service: 0.0369,
    },
    {
      market: "Turkey",
      currency: "$US",
      marketing: 0.0109,
      utility: 0.0053,
      authentication: 0.0083,
      authenticationInternational: null,
      service: 0.003,
    },
    {
      market: "United Arab Emirates",
      currency: "$US",
      marketing: 0.0384,
      utility: 0.0157,
      authentication: 0.0178,
      authenticationInternational: null,
      service: 0.019,
    },
    {
      market: "United Kingdom",
      currency: "$US",
      marketing: 0.0529,
      utility: 0.022,
      authentication: 0.0358,
      authenticationInternational: null,
      service: 0.0388,
    },
    {
      market: "North America",
      currency: "$US",
      marketing: 0.025,
      utility: 0.004,
      authentication: 0.0135,
      authenticationInternational: null,
      service: 0.0088,
    },
    {
      market: "Rest of Africa",
      currency: "$US",
      marketing: 0.0225,
      utility: 0.0061,
      authentication: 0.0144,
      authenticationInternational: null,
      service: 0.0363,
    },
    {
      market: "Rest of Asia Pacific",
      currency: "$US",
      marketing: 0.0732,
      utility: 0.0157,
      authentication: 0.0425,
      authenticationInternational: null,
      service: 0.0224,
    },
    {
      market: "Rest of Central & Eastern Europe",
      currency: "$US",
      marketing: 0.086,
      utility: 0.0353,
      authentication: 0.0557,
      authenticationInternational: null,
      service: 0.025,
    },
    {
      market: "Rest of Latin America",
      currency: "$US",
      marketing: 0.074,
      utility: 0.0113,
      authentication: 0.0445,
      authenticationInternational: null,
      service: 0.0423,
    },
    {
      market: "Rest of Middle East",
      currency: "$US",
      marketing: 0.0341,
      utility: 0.0157,
      authentication: 0.0178,
      authenticationInternational: null,
      service: 0.0218,
    },
    {
      market: "Rest of Western Europe",
      currency: "$US",
      marketing: 0.0592,
      utility: 0.03,
      authentication: 0.0378,
      authenticationInternational: null,
      service: 0.0397,
    },
    {
      market: "Other",
      currency: "$US",
      marketing: 0.0604,
      utility: 0.0077,
      authentication: 0.0304,
      authenticationInternational: null,
      service: 0.0145,
    },
  ],
} as const;
