apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

commonLabels:
  environment: prd

patchesStrategicMerge:
- typebot-builder-configmap.yaml
- typebot-builder-ingress.yaml
- typebot-viewer-configmap.yaml
- typebot-viewer-ingress.yaml
- typebot-viewer-cpu-patch.yaml
