// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { hackernewsBlock } from ".";
import { auth } from "./auth";

export const hackernewsBlockSchema = parseBlockSchema(hackernewsBlock);
export const hackernewsCredentialsSchema = parseBlockCredentials(
  hackernewsBlock.id,
  auth.schema,
);
