// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { elevenlabsBlock } from "./index";

export const elevenlabsBlockSchema = parseBlockSchema(elevenlabsBlock);
export const elevenlabsCredentialsSchema = parseBlockCredentials(
  elevenlabsBlock.id,
  auth.schema,
);
