name: Daily database cleanup

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/scripts
    env:
      DATABASE_URL: '${{ secrets.DATABASE_URL }}'
      ENCRYPTION_SECRET: '${{ secrets.ENCRYPTION_SECRET }}'
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXT_PUBLIC_VIEWER_URL: 'http://localhost:3001'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
      - run: pnpm i --frozen-lockfile
      - run: pnpm turbo run db:cleanDatabase
