name: Publish @typebot.io/react package to NPM

on:
  push:
    tags:
      - "react-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"
      - run: bun install
      - run: bunx nx build react
      - run: cd packages/embeds/react && bun publish --access public
