name: Publish @typebot.io/nextjs package to NPM

on:
  push:
    tags:
      - "nextjs-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bunx turbo build --filter=@typebot.io/nextjs...
      - run: bun run npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: cd packages/embeds/nextjs && bun run npm publish --no-git-checks --access public
