name: Send chats limit alert emails

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/scripts
    env:
      DATABASE_URL: '${{ secrets.DATABASE_URL }}'
      ENCRYPTION_SECRET: '${{ secrets.ENCRYPTION_SECRET }}'
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXT_PUBLIC_VIEWER_URL: 'http://localhost:3001'
      TELEMETRY_WEBHOOK_URL: '${{ secrets.TELEMETRY_WEBHOOK_URL }}'
      TELEMETRY_WEBHOOK_BEARER_TOKEN: '${{ secrets.TELEMETRY_WEBHOOK_BEARER_TOKEN }}'
      SMTP_USERNAME: '${{ secrets.SMTP_USERNAME }}'
      SMTP_PASSWORD: '${{ secrets.SMTP_PASSWORD }}'
      SMTP_HOST: '${{ secrets.SMTP_HOST }}'
      SMTP_PORT: '${{ secrets.SMTP_PORT }}'
      NEXT_PUBLIC_SMTP_FROM: '${{ secrets.NEXT_PUBLIC_SMTP_FROM }}'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
      - run: pnpm i --frozen-lockfile
      - run: pnpm turbo run sendAlertEmails
